export {
  ArrowPathIcon as RefreshIcon,
  ArrowPathIcon as SwitchHorizontalIcon,
  Bars3Icon as MenuIcon,
  CircleStackIcon as DatabaseIcon,
  CircleStackIcon as DatabasePerformanceIcon,
  ClockIcon,
  CodeBracketIcon as ApiPerformanceIcon,
  CodeBracketIcon as CodeIcon,
  CogIcon as SettingsIcon,
  CommandLineIcon as SqlStatementsIcon,
  ComputerDesktopIcon as DesktopComputerIcon,
  CubeIcon as SpansIcon,
  CubeTransparentIcon as TracesIcon,
  DevicePhoneMobileIcon as DeviceMobileIcon,
  DeviceTabletIcon,
  DocumentDuplicateIcon,
  DocumentIcon as DocumentReportIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon as ErrorIcon,
  EyeIcon,
  GlobeAltIcon as NetworkPerformanceIcon,
  HomeIcon,
  InboxArrowDownIcon as TemplatesIcon,
  InboxIcon,
  InboxIcon as MailIcon,
  InformationCircleIcon as InfoIcon,
  LinkIcon,
  ListBulletIcon as OperationsIcon,
  MagnifyingGlassCircleIcon as InspectorIcon,
  MapIcon,
  NewspaperIcon as ErdIcon,
  PaperClipIcon,
  PhotoIcon as OGTagPreviewIcon,
  Square2StackIcon as CollectionIcon,
  Square2StackIcon as DashboardIcon,
  TableCellsIcon as TableIcon,
  VariableIcon,
} from '@heroicons/react/24/outline'

export { GraphQLIcon } from './GraphQLIcon'
export { GraphQLIcon as GraphQLPerformanceIcon } from './GraphQLIcon'
