export {
  ArrowPathIcon as RefreshIcon,
  ArrowsRightLeftIcon,
  ArrowsRightLeftIcon as HorizontalIcon,
  ArrowsUpDownIcon as VerticalIcon,
  Bars3Icon as MenuIcon,
  BoltIcon as MonitoringIcon,
  ChatBubbleLeftEllipsisIcon as DiscourseIcon,
  CircleStackIcon as DatabaseIcon,
  CircleStackIcon as DatabasePerformanceIcon,
  ClockIcon,
  CodeBracketIcon as ApiPerformanceIcon,
  CodeBracketIcon,
  Cog8ToothIcon as SettingsIcon,
  CommandLineIcon as SqlStatementsIcon,
  ComputerDesktopIcon,
  CubeIcon as SpansIcon,
  CubeTransparentIcon as TracesIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  DocumentChartBarIcon,
  DocumentDuplicateIcon,
  DocumentMagnifyingGlassIcon as SearchDocumentsIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon as ErrorIcon,
  EyeIcon,
  GlobeAltIcon as NetworkPerformanceIcon,
  HomeIcon,
  InboxArrowDownIcon as TemplatesIcon,
  InboxIcon,
  EnvelopeIcon,
  EnvelopeIcon as MailerIcon,
  InformationCircleIcon as InfoIcon,
  LinkIcon,
  ListBulletIcon as OperationsIcon,
  MagnifyingGlassCircleIcon as InspectorIcon,
  MagnifyingGlassIcon as SearchIcon,
  MapIcon,
  NewspaperIcon as ErdIcon,
  PaperClipIcon,
  PhotoIcon as OGTagPreviewIcon,
  RectangleStackIcon,
  Square2StackIcon as DashboardIcon,
  TableCellsIcon,
  VariableIcon,
  ViewColumnsIcon as PlaygroundIcon,
  XMarkIcon as CloseIcon,
} from '@heroicons/react/24/outline'

export {
  RxDiscordLogo as DiscordIcon,
  RxGithubLogo as GitHubIcon,
} from 'react-icons/rx'

export { DocumentDuplicateIcon as DocumentDuplicateSolidIcon } from '@heroicons/react/20/solid'

export { GraphQLIcon } from './GraphQLIcon'
export { GraphQLIcon as GraphQLPerformanceIcon } from './GraphQLIcon'
